# Forge Start Workflow
# Executes from-scratch PRD creation workflow
param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectName
)

$ForgeRoot = "C:\Users\User\AI\Systems\Forge"
$CorePath = "$ForgeRoot\core"
$LibPath = "$ForgeRoot\lib"

# Step 1: Create project
Write-Host ""
Write-Host "=============================================================" -ForegroundColor Cyan
Write-Host "           FORGE START WORKFLOW - $ProjectName              " -ForegroundColor Cyan
Write-Host "=============================================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "[1/7] Creating project..." -ForegroundColor Yellow
& "$ForgeRoot\scripts\forge.ps1" start $ProjectName

$ProjectPath = "C:\Users\User\AI\Projects\$ProjectName"
if (-not (Test-Path $ProjectPath)) {
    Write-Host "[ERROR] Project creation failed" -ForegroundColor Red
    exit 1
}

Write-Host "[OK] Project created" -ForegroundColor Green
Write-Host ""

# Step 2: Load discovery questions
Write-Host "[2/7] Loading discovery questions..." -ForegroundColor Yellow
$questionsPath = "$LibPath\questions\core-discovery.json"
if (-not (Test-Path $questionsPath)) {
    Write-Host "[ERROR] Questions file not found" -ForegroundColor Red
    exit 1
}

$questions = Get-Content $questionsPath | ConvertFrom-Json
Write-Host "[OK] Loaded $($questions.questions.Count) discovery questions" -ForegroundColor Green
Write-Host ""

# Step 3: Interactive Q&A
Write-Host "[3/7] Discovery Phase - Answer questions to build PRD" -ForegroundColor Yellow
Write-Host ""

$answers = @{}

foreach ($q in $questions.questions) {
    Write-Host "$($q.question)" -ForegroundColor Cyan
    if ($q.examples) {
        Write-Host "Examples:" -ForegroundColor Gray
        foreach ($example in $q.examples) {
            Write-Host "  - $example" -ForegroundColor Gray
        }
    }

    $answer = Read-Host "Answer"
    $answers[$q.id] = $answer
    Write-Host ""
}

Write-Host "[OK] Discovery phase complete" -ForegroundColor Green
Write-Host ""

# Step 4: Generate PRD from answers
Write-Host "[4/7] Generating PRD from answers..." -ForegroundColor Yellow

$prdContent = @"
# $ProjectName - PRD

## Executive Summary

$($answers.problem)

**Target Users**: $($answers.target_users)
**Primary Goal**: $($answers.primary_goal)

## User Personas

### Persona 1: Primary User
- **Profile**: $($answers.target_users)
- **Goals**: $($answers.primary_goal)
- **Pain Points**: $($answers.problem)

## Features & Requirements

### Must-Have (MVP)

$($answers.key_features)

## Technical Foundation

### Tech Stack

**Frontend**: TBD
**Backend**: TBD
**Database**: TBD
**Auth**: TBD
**Hosting**: TBD

### Non-Functional Requirements

**Performance**: TBD
**Security**: TBD
**Scalability**: TBD

## Success Metrics

**Primary KPIs**: TBD

## MVP Scope & Roadmap

### Phase 1: MVP (Months 1-3)
- Core Features: TBD
- Target: Prove product-market fit

---

**Generated by Forge v1.0**
"@

Set-Content "$ProjectPath\prd.md" $prdContent
Write-Host "[OK] PRD generated" -ForegroundColor Green
Write-Host ""

# Step 5: Run status check
Write-Host "[5/7] Checking PRD confidence..." -ForegroundColor Yellow
Push-Location $ProjectPath
& "$ForgeRoot\scripts\forge.ps1" status
Pop-Location
Write-Host ""

# Step 6: Setup GitHub foundation
Write-Host "[6/7] Setting up GitHub foundation..." -ForegroundColor Yellow
& "$ForgeRoot\scripts\forge.ps1" setup-repo $ProjectName
Write-Host ""

# Step 7: Next steps
Write-Host "[7/7] Workflow complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Review and enhance PRD at: $ProjectPath\prd.md" -ForegroundColor White
Write-Host "  2. Run 'forge status' to check confidence" -ForegroundColor White
Write-Host "  3. Fill gaps until 95% confidence" -ForegroundColor White
Write-Host "  4. Initialize git: cd $ProjectPath && git init" -ForegroundColor White
Write-Host "  5. Create GitHub repo: gh repo create $ProjectName --private --source=. --remote=origin" -ForegroundColor White
Write-Host "  6. Generate issues: forge generate-issues" -ForegroundColor White
Write-Host ""
