#!/bin/bash

# Enterprise UI Builder Main Launcher
# Usage: ./enterprise [command]

cd "$(dirname "$0")"

if [ $# -eq 0 ]; then
    # No arguments - show boot display
    node auto-loader.js
else
    # Pass command to commands handler
    node commands.js "$1"
fi